### ISSUE TITLE
moveq optimization also for move.w ?

### ISSUE THREAD

**Issue by honitos** [earok/chocolate_blitzbasic2#3]
The optimization is cool!

I suggest you add the optimization to the .word-branch as well.

BTW there is a datatype checking that jumps to the ".word" or ".long"-branches right before your change.
In case you are not familiar with the datatype constants used in this code section, here they are:

#byte=1
#word=2
#long=3
#quick=4
#float=5
#string=7 ; of course not handled in this section

So you could implement an optimization for a byte value as well (that is treated as a word value at this point)

**Comment by earok** [comment]
Thanks honitos!

Suggested fix has been applied
